### ISSUE TITLE
SettingsBlock.dbiFallbackProductionConfig is not decrypting

### ISSUE THREAD

**Issue by maxktz** [ntqbit/tdesktop-decrypter#5]
Bro, thanks a lot, but the only thing is not decrypting is this:

<img width="724" alt="image" src="https://github.com/user-attachments/assets/cab76587-9169-4e3b-aa86-ace661a71f85" />

It is still being bytes

And, when I additionally pass `--json` for sure I get `TypeError: Object of type bytes is not JSON serializable`

---
### Steps to reproduce:
I tried to decode almost empty tdata, without account, but with proxy in settings.

So I opened fresh telegram, it has created tdata, I added proxy and closed it without logging into accout.

---
Also, can you contact me in telegram [maxktz](https://t.me/maxktz), please? wanna ask a question

**Comment by ntqbit** [comment]
Hello.

I added support for `SettingsBlock.dbiFallbackProductionConfig` decoding.
The `dbiApplicationSettings` block is still undecoded (added in todo), but I fixed the output (for json as well) so that bytes are displayed as hex strings.

If you specifically need the `dbiApplicationSettings` value and are willing to contribute, I'd be glad to accept a PR ([settings encoding scheme](https://github.com/telegramdesktop/tdesktop/blob/4505a2bf2dbb73185b4bb8b18b2aab721765bb7e/Telegram/SourceFiles/core/core_settings.cpp#L411)).

For any questions you can contact me at ntqbit@proton.me.
